### ISSUE TITLE
Allow @ in Instagram

### ISSUE THREAD

**Issue by Katreque** [gkucmierz/social-links#14]
Is it possible to allow Instagram user with @?

![Sem título](https://user-images.githubusercontent.com/11504942/91764783-430d3f80-ebae-11ea-8e35-a2b45c8918e9.png)

**Comment by gkucmierz** [comment]
Why?

Instagram links don't work with `@`

Check this example:
https://www.instagram.com/bitcoin
https://www.instagram.com/@bitcoin

**Comment by Katreque** [comment]
That's true, however, as user mentions on Instagram uses @, some users refers to profiles with @. 

It could be valid and the sanitized url redirect to the valid form:

Profile: @test
isValid: True
sanitizedUrl: https://www.instagram.com/test

**Comment by gkucmierz** [comment]
I get it. You mean `profileId` alone.
I fixed it in `v1.3.1` patch:

https://www.npmjs.com/package/social-links/v/1.3.1
