### ISSUE TITLE
No support for company linkedIn links

### ISSUE THREAD

**Issue by deniselashlley** [gkucmierz/social-links#23]
Is there support for LinkedIn links that have this URL 'https://www.linkedin.com/company/nhs/' instead of the standard
as I am getting an error? that is not matching.

**Comment by gkucmierz** [comment]
That's true.

I suggest you to add new profile for example `linkedin-company` to handle this case.

**Comment by deniselashlley** [comment]
how would you do that?
`import { SocialLinks, Profile } from 'social-links';

const socialLinks = new SocialLinks();
const profileMatches: Profile[] = [ ... ]; // 

socialLinks.addProfile('linkedin-company', profile);`

**Comment by gkucmierz** [comment]
Like that for example:

```ts
import { SocialLinks, Profile } from 'social-links';

const socialLinks = new SocialLinks();
const profileMatches: Profile[] = [
  {
    match: '(https?://)?(www.)?linkedin.com/company/({PROFILE_ID})/?', group: 3, type: TYPE_DESKTOP,
    pattern: 'https://linkedin.com/company/{PROFILE_ID}'
  },
  { match: '({PROFILE_ID})', group: 1 },
];

socialLinks.addProfile('linkedin-company', profile);
```
