### ISSUE TITLE
running in Browser possible?

### ISSUE THREAD

**Issue by MR4online** [gkucmierz/social-links#29]
Is it possible to run this lib in browser environments?
I tried, but I didn't succeed. Looks like NodeJs only?

**Comment by jcharlesworthuk** [comment]
Dunno if this will help or you even still need this, but the demo site linked in README.md runs it in the browser so must be possible https://awesome-web-tools.web.app/social-links

**Comment by gkucmierz** [comment]
Yes it is possible as @jcharlesworthuk noticed.
