### ISSUE TITLE
Add "youtu.be" url to the YouTube profile matching

### ISSUE THREAD

**Issue by mindblender** [gkucmierz/social-links#36]
When a user copies a YouTube link via the "share" icon, the URL is formatted as "https://youtu.be/8YUpvQ3DX7I". 

Would it be possible to add the short YouTube URL as an additional pattern?  It appears that YouTube generates that URL on both mobile and desktop browsers.

Thanks!

**Comment by gkucmierz** [comment]
It is not actually profile link but content link.

**Comment by mindblender** [comment]
Thanks for the comment.  

Should it not be able to be validated using the `socialLinks.isValid()` method since it is a valid YouTube link that is provided by YouTube?

**Comment by gkucmierz** [comment]
It should not be valid actually.

This is library for social links, so it's meant to validate links to profiles.

But you provided link to content, not profile.

**Comment by mindblender** [comment]
Ok, thank you for the clarification.
