### ISSUE TITLE
`socialLinks.sanitize` misformats valid Youtube urls (inserts `@` in the url)

### ISSUE THREAD

**Issue by AndrwM** [gkucmierz/social-links#46]
Hey all, thanks much for this great utility.

In using `socialLinks.sanitize` for our implementation:
- Given a url of `https://www.youtube.com/channel/UCBTKd-zHSdr8POH-Y7LyPWg`
- `socialLinks.sanitize` will format the url as `https://www.youtube.com/channel/@UCBTKd-zHSdr8POH-Y7LyPWg`
- This behavior can be replicated in the demo site: https://gkucmierz.github.io/social-links-app/

#### Demo site preview
<img width="608" alt="Andrew McIntee Screencap 2023-04-25 at 13 28 20@2x" src="https://user-images.githubusercontent.com/565743/234355717-abc3bc32-43c5-41d8-9702-23d9ae84887b.png">

---

This was ultimately not a dealbreaker for us, we were able to use an alternative strategy in our particular implementation. However I wanted to raise this with y'all for visibility.

Appreciate the efforts, all the best~

**Comment by gkucmierz** [comment]
You are trying to sanitize channel link.
I think channels are different things than profiles. And these two things should be served separately.
Right now there is no profile for channels. If you need it you can do PR with profile 'youtubeChannels'.
I will merge it.
