### ISSUE TITLE
Support Fediverse Links

### ISSUE THREAD

**Issue by borgmon** [gkucmierz/social-links#50]
Please add support for Fediverse social links like mastodon or lemmy. 
lemmy example: (random mod from lemmy.world)
`@MichelleG@lemmy.world`
->
https://lemmy.world/u/MichelleG

mastodon example: 
`@Mastodon@mastodon.social`
->
https://mastodon.social/@Mastodon

this require a refactor of the code base, since the base URL is dynamic. 
The matcher needs to parse the instance URL and use it to generate URLs. 
detect() is not possible, since it's dynamic.

This would be really nice to have.

**Comment by gkucmierz** [comment]
I added `lemmy_world`.

I think mastodon social links can all be added in single profile.
I added 3 of them right now.

And it should detect and sanitize correct links right now.
And also it is possible detection single ids like: '@user@mastodon.social`.

What do you think about this?

I was thinking about rebuilding this package and download possible links from external source but I think it is not good idea beacause:
- package behaviour will be not predictable then,
- it will depend on exisitng some kind of `fetch` function in execution enviroment,
- and also package will not be ready right away but after promise (after fetch data).

So I decided to add few of them manually to package.

**Comment by gkucmierz** [comment]
merged in version `1.14`

**Comment by borgmon** [comment]
Hello! Thanks for the update! The patch works for now. 
Since it’s the dynamic nature of Fediverse, having list of common instances isn’t going to cut it in the long run. I agree, loading a dynamic list is introducing unexpected behavior and security risks. 

Maybe instead of thinking how to fit Fediverse profile into current schema, think how to fit traditional socials into a new schema that user can define a base url.
