### ISSUE TITLE
If username detected it should not contain the exact domain name

### ISSUE THREAD

**Issue by sajrus33** [gkucmierz/social-links#7]
If username detected it should not contain the exact domain name
![Zrzut ekranu 2020-07-24 o 21 16 51](https://user-images.githubusercontent.com/45123640/88427696-bd9ab080-cdf3-11ea-889e-50014c056fe5.png)
![Zrzut ekranu 2020-07-24 o 21 21 12](https://user-images.githubusercontent.com/45123640/88427698-be334700-cdf3-11ea-9b01-8eb542a92ca9.png)

**Comment by gkucmierz** [comment]
Can you provide more details?

It seems to look good:

<img width="637" alt="Zrzut ekranu 2020-07-25 o 13 05 50" src="https://user-images.githubusercontent.com/739084/88455680-a30a1b00-ce77-11ea-9f6c-0024d4e31920.png">

<img width="588" alt="Zrzut ekranu 2020-07-25 o 13 05 56" src="https://user-images.githubusercontent.com/739084/88455683-a6050b80-ce77-11ea-873f-2070d517f0bc.png">

https://awesome-web-tools.web.app/social-links

**Comment by gkucmierz** [comment]
I still don't know what do you mean.
I am closing this issue.
